from __future__ import annotations

import json
import os
from typing import Any, Mapping

from openai import OpenAI
from pydantic import BaseModel, Field


DEFAULT_MODEL = "gpt-5.4-mini"

ALLOWED_EXPLANATION_FIELDS = (
    "case_summary",
    "reviewer_note",
    "next_step_message",
)


class StructuredExplanation(BaseModel):
    """Non-authoritative explanation content generated by the LLM."""

    case_summary: str = Field(
        min_length=1,
        max_length=600,
    )
    reviewer_note: str = Field(
        min_length=1,
        max_length=500,
    )
    next_step_message: str = Field(
        min_length=1,
        max_length=400,
    )


def _as_dict(value: object) -> dict[str, Any]:
    """Return a plain dictionary for a mapping, otherwise an empty dict."""
    if isinstance(value, Mapping):
        return dict(value)

    return {}


def _get_model_name(model: str | None = None) -> str:
    """Return an explicitly supplied or environment-configured model name."""
    selected_model = (
        model
        or os.getenv("OPENAI_EXPLANATION_MODEL")
        or DEFAULT_MODEL
    ).strip()

    if not selected_model:
        raise ValueError("A non-empty OpenAI model name is required.")

    return selected_model


def _build_explanation_input(
    tool_result: Mapping[str, Any],
) -> dict[str, Any]:
    """
    Build a minimal, authoritative-only context for the LLM.

    No raw claim narrative, payout amount, or unverified inference is sent.
    """
    result = _as_dict(tool_result)
    decision = _as_dict(result.get("deterministic_decision"))

    required_fields = [
        "claim_id",
        "triage_outcome",
        "triggering_rule_id",
        "precedence_stage",
        "decision_reason",
        "rule_trace",
        "system_limitations",
        "decision_support_only",
    ]

    missing_fields = [
        field_name
        for field_name in required_fields
        if field_name not in decision
    ]

    if missing_fields:
        raise ValueError(
            "deterministic_decision is missing required fields: "
            + ", ".join(missing_fields)
        )

    return {
        "claim_id": decision["claim_id"],
        "triage_outcome": decision["triage_outcome"],
        "triggering_rule_id": decision["triggering_rule_id"],
        "precedence_stage": decision["precedence_stage"],
        "decision_reason": decision["decision_reason"],
        "rule_trace": decision["rule_trace"],
        "system_limitations": decision["system_limitations"],
        "decision_support_only": decision["decision_support_only"],
        "authority_notice": (
            "The deterministic decision is authoritative. "
            "The explanation must not alter or reinterpret it."
        ),
    }


def build_openai_explanation_proposal(
    tool_result: Mapping[str, Any],
    model: str | None = None,
) -> dict[str, str]:
    """
    Generate a structured, non-authoritative explanation proposal.

    The returned fields are intended to pass through response_guardrail.py.
    They must never be used to alter deterministic eligibility routing.
    """
    if not os.getenv("OPENAI_API_KEY"):
        raise EnvironmentError(
            "OPENAI_API_KEY is not available in the environment."
        )

    selected_model = _get_model_name(model=model)
    explanation_input = _build_explanation_input(tool_result)

    instructions = """
You are an explanation assistant for a device-protection claims-triage
decision-support workflow.

Use only the authoritative deterministic decision data supplied by the user.

You must never:
- change, recommend changing, or reinterpret the triage outcome;
- state that a claim is approved, paid, settled, finally denied, or rejected;
- infer fraud, customer fault, intent, coverage, evidence, or policy facts
  that are not explicitly provided;
- introduce new rule IDs, policy terms, or claim facts;
- discourage, prevent, or replace authorised human review or escalation;
- remove or minimise listed system limitations.

Write neutral, concise operational guidance for an analyst.

Describe the result only as a system triage recommendation, not as a final
approval, denial, settlement, or determination.

The reviewer_note must:
- state that the deterministic outcome is the system's triage recommendation;
- state that authorised reviewers may follow approved review, escalation, or
  exception-handling procedures where appropriate;
- preserve relevant system limitations.

The next_step_message must describe an operational next step without implying
that the claim has been finally approved, denied, rejected, paid, or settled.

Do not tell an analyst that they must not reassess, reopen, review, challenge,
reinterpret, or escalate a case. Do not use wording such as:
"do not reassess", "do not reopen", or "do not reinterpret".

Use the supplied rule trace only as supporting context.
The deterministic outcome is authoritative for this system response and is
decision-support-only. Authorised human reviewers retain responsibility for
applying approved operational procedures.
""".strip()

    client = OpenAI()

    response = client.responses.parse(
        model=selected_model,
        instructions=instructions,
        input=json.dumps(
            explanation_input,
            ensure_ascii=False,
            default=str,
        ),
        text_format=StructuredExplanation,
    )

    parsed_output = response.output_parsed

    if parsed_output is None:
        raise ValueError(
            "OpenAI returned no structured explanation output."
        )

    return parsed_output.model_dump()